### ISSUE TITLE
change 'request' type on egithub_webhook

### ISSUE THREAD

**Issue by ferigis** [inaka/erlang-github#123]
Currently the request type is
```erlang
#{headers => map(), body => map()}.
```
The `body` can't be a map since it is going to be decoded with `egithub_json:decode(Body)`

**Comment by mfelsche** [comment]
this is already fixed by 65ff9de6f4ae8c7a68885a9d44c80c944427f7ad
isnt it?

**Comment by elbrujohalcon** [comment]
it is
