### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by tgrk** [inaka/erlang-github#82]
I am no longer able to build this project (with good old `rebar`). I just updated my fork from upstream and things are broken so I can't send a PR . It looks like one needs to have `hex` or/and `rebar3` installed on his machine now. It might be a good idea to specify that in docs as a requirement.

**Comment by elbrujohalcon** [comment]
@tgrk you're right. Our main target was (and still is) erlang.mk. We started slowly moving things to hex not so long ago, and by that time we unwillingly dropped support for rebar.
Maybe you can send us a PR with a (I think) `rebar.config.script` file that allows rebar[3] users to compile the project with whatever rebar version they like the most?

**Comment by tgrk** [comment]
Sure will do. It will take some time for `rebar3` to become standard.
